public class Rosalind2{
    private String DNA;
    private String RNA;

    public Rosalind2 (String data){
	DNA = data;
	RNA = "";
    }
    
    public void alter(String data){
	for (int i = 0; i < data.length(); i++){
	    char c = data.charAt(i);
	    if (c == 'A'){
		RNA += 'A';}
	    else if (c == 'C'){
		RNA += 'C';}
	    else if (c == 'G'){
		RNA += 'G';}
	    else if (c == 'T'){
		RNA += 'U';}
	}
    }

    public String solve(){
	alter(DNA);
	return RNA;
    }

    //main

    public static void main (String[]args){
	Rosalind2 a = new Rosalind2("GGGTTATCAAATTGCTAGTCGCAACCGCCTTCGCCTTGGTTTCTGTGGGTTCGAAATTGTTTCGAAATGAAGCCCCCACCCCCCGTGAAGCCTCAACTCCGTAACTTGGTTGTTGGCATCCTTCGAGCCCTGTGTCGAATCTAGCTAGATTGGCGAGTCGCCAATTCTCCACGCATGAACGTTTTATTTGCTACCTCAGGCAGTCATATCGTACCTCGGAGGGGGTCCTCGCGACCTCGTGTTTTATACAGTGCCACTTACGCTATCTTCCTTGCCTAAGTCGAGGCTTAGTAGAAGGACCTGTAGATTATCTTGGTGGTCCGGTCCCTGCTGATAGTCAATGACTTCCGGAAGAATTACCTTGATAGGACTTCCAACCTATGGCCATCAGCTCGCTCATGGTATCGTTACGGACCTATTTTGTATAGGCTACTGGCCTCCCGGGGCGGTAAGTTCGATCCGGAGGTGCGAGCCATAAATAATAGAAACCATTCCCGAGTGCAGACGCGTTGATCGGCGAAGGTTCCCGGGGGCAGGGGACCCTACTTCGCCTTTGAGACACTCACTGTAAGATAACCTACTCACCAACAGCGCCGGTGTTGGCGAAGGCCTGGTTGCGTCTAGGCGTCAAGTGTGCAGAGACCCAGGGTTGGGGGGGAATCTGATGTGTAACTGCTTCGAGCCAGAAAACTCCCCACCAGCCGCTGTCTCGGGACACGCCGCAACTAATGCATCCAGCTCTTCCGAAATTAGGGTCCTCGTATAATCGCCGCCGTTGCCGCACGGGGACGTGTGTACGTAACTCTTAGGGGGCAACAGAGTGGGGGGCTAGGCCACCCGGTTACCTGAGCGTCTCTAGATGGTTTTCCTCTAGGAGTTGCAACCGGACATAGACGCCGTTCATATTTATCTAGGCCTTTTGGTCAACAAGTTCATAGACAGGTGAGTGTAGAGTCGCGGAAAGGCATAGTGCTCGACTAGTTCAAACGTCC");
	System.out.println(a.solve());
    }
}
       
